---
- hosts: all
  become: true

  vars_files:
    - config.yml

  tasks:
    - import_role:
        name: glillico.configure_firewall
      when: configure_firewall
      tags: ['firewall']

    - import_role:
        name: glillico.set_hostname
      when: set_hostname
      tags: ['hostname']

    - import_role:
        name: glillico.update_pkgs
      when: update_pkgs
      tags: ['update_pkgs']

    - name: Flush handlers
      meta: flush_handlers

    - import_role:
        name: glillico.reboot_server
      when: reboot_server_after_updates

    - import_role:
        name: glillico.setup_users
      when: setup_users
      tags: ['users']

    - import_role:
        name: glillico.setup_ssh_keys
      when: setup_ssh_keys
      tags: ['ssh_keys']

    - import_role:
        name: glillico.configure_sshd
      when: configure_sshd
      tags: ['sshd']

    - import_role:
        name: glillico.copy_etc_issue
      when: copy_etc_issue
      tags: ['issue']

    - import_role:
        name: glillico.configure_ntp
      when: configure_ntp
      tags: ['ntp']

    - import_role:
        name: glillico.install_fail2ban
      when: install_fail2ban
      tags: ['fail2ban']

    - import_role:
        name: glillico.auto_pkg_updates
      when: auto_pkg_updates
      tags: ['auto_pkg_updates']

    - import_role:
        name: glillico.configure_sudo
      when: configure_sudo
      tags: ['configure_sudo']

    - import_role:
        name: glillico.sync_sudo
      when: sync_sudo
      tags: ['sync_sudo']

    - import_role:
        name: glillico.add_rm_pkgs
      when: add_rm_pkgs
      tags: ['add_rm_pkgs']

    - import_role:
        name: glillico.manage_selinux
      when: manage_selinux
      tags: ['selinux']

    - import_role:
        name: glillico.regenerate_ssh_host_keys
      when: regenerate_ssh_host_keys
      tags: ['host_keys']

    - name: Flush handlers
      meta: flush_handlers

    - import_role:
        name: glillico.reboot_server
      when: reboot_server_after_build

    - import_role:
        name: glillico.install_docker
      when: install_docker
      tags: ['docker']

    - name: Flush handlers
      meta: flush_handlers

    - import_role:
        name: glillico.reboot_server
      when: reboot_server_final
      tags: ['reboot']

    - name: BUILD COMPLETE
      ansible.builtin.debug:
        msg: 'NOTE: sshd hostkeys have been changed.'
      when: regenerate_ssh_host_keys
